"use strict";

const crypto = require("crypto");
const {
  SlashCommandBuilder, PermissionFlagsBits, ChannelType, EmbedBuilder,
  ActionRowBuilder, StringSelectMenuBuilder, RoleSelectMenuBuilder,
  ChannelSelectMenuBuilder, ButtonBuilder, ButtonStyle, ModalBuilder,
  TextInputBuilder, TextInputStyle, AttachmentBuilder
} = require("discord.js");
const { loadData, saveData } = require("./database.js");
const { createErrorEmbed, createSuccessEmbed } = require("./embeds.js");
const { canRunLeagueAdmin } = require("./permissions.js");

const COLORS = { main: 0x5865f2, pending: 0xf1c40f, accept: 0x57f287, reject: 0xed4245 };
const MAX_FORMS = 200, MAX_QUESTIONS = 100, MAX_OPTIONS = 25;
const DANGEROUS_ROLE_PERMISSIONS = [
  PermissionFlagsBits.Administrator,
  PermissionFlagsBits.ManageGuild,
  PermissionFlagsBits.ManageRoles,
  PermissionFlagsBits.ManageChannels,
  PermissionFlagsBits.BanMembers,
  PermissionFlagsBits.KickMembers,
  PermissionFlagsBits.ManageWebhooks
];
function cfg(data, guildId) {
  data.settings.applications ??= {};
  data.settings.applications[guildId] ??= { reviewChannelId: null, adminRoleId: null, panelChannelId: null, panelMessageId: null, forms: {}, submissions: {}, history: {} };
  const c = data.settings.applications[guildId]; c.forms ??= c.types ?? {}; c.submissions ??= {}; c.history ??= {}; return c;
}
function slug(s) { return s.toLowerCase().trim().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "").slice(0, 80); }
function id() { return crypto.randomBytes(10).toString("hex"); }
function admin(i, c, data) { return Boolean(i.memberPermissions?.has(PermissionFlagsBits.Administrator) || (c.adminRoleId && i.member?.roles?.cache?.has(c.adminRoleId)) || canRunLeagueAdmin(i, data)); }
function roleList(v) { return Array.isArray(v) ? v.filter(x => typeof x === "string") : []; }
function safeApplicationRole(guild, roleId) {
  const role = guild.roles.cache.get(roleId);
  return Boolean(role && role.id !== guild.id && !role.managed && role.editable && !role.permissions.has(DANGEROUS_ROLE_PERMISSIONS));
}
function normalizeForm(f) {
  f.questions ??= [];
  f.actions ??= { submit: { add: [], remove: [] }, accept: { add: [f.roleId].filter(Boolean), remove: [] }, reject: { add: [], remove: [] } };
  for (const k of ["submit", "accept", "reject"]) f.actions[k] ??= { add: [], remove: [] };
  f.requiredRoles = roleList(f.requiredRoles); f.blockedRoles = roleList(f.blockedRoles); f.reviewerRoles = roleList(f.reviewerRoles);
  f.cooldownSeconds = Number.isFinite(f.cooldownSeconds) ? Math.max(0, Math.floor(f.cooldownSeconds)) : 0;
  f.questions = f.questions.map((q, n) => ({ id: q.id || id(), label: q.label || q.question || `Question ${n + 1}`, type: q.type || "paragraph", required: q.required !== false, options: Array.isArray(q.options) ? q.options : [], regex: q.regex || null, placeholder: q.placeholder || null, min: q.min ?? null, max: q.max ?? null, roleCount: q.roleCount || 1 }));
  return f;
}
function form(c, fid) { const f = c.forms[fid]; return f ? normalizeForm(f) : null; }
function formName(f) { return `${f.emoji || "📋"} ${f.name}`; }
function hasRoles(member, ids) { return ids.length === 0 || ids.every(r => member.roles.cache.has(r)); }
function hasBlocked(member, ids) { return ids.some(r => member.roles.cache.has(r)); }
function reviewer(i, c, data, f) { return admin(i, c, data) || Boolean(f?.reviewerRoles?.some(r => i.member?.roles?.cache?.has(r))); }
function actionsFor(f, stage) { return f.actions?.[stage] || { add: [], remove: [] }; }
function publicPanel(guild, c) {
  const forms = Object.entries(c.forms).slice(0, 25);
  const menu = new StringSelectMenuBuilder().setCustomId("application_select").setPlaceholder("Select an application...").addOptions(forms.map(([fid, f]) => ({ label: f.name.slice(0, 100), description: `Apply for ${f.name}`.slice(0, 100), value: fid, ...(f.emoji ? { emoji: f.emoji } : {}) })));
  return { embeds: [new EmbedBuilder().setColor(COLORS.main).setAuthor({ name: guild.name, iconURL: guild.iconURL({ size: 128 }) ?? undefined }).setTitle("Applications").setDescription("Select an application below to begin. Your answers are collected privately in this server.")], components: [new ActionRowBuilder().addComponents(menu)] };
}
function adminHome(guild, c) { const forms = Object.values(c.forms); return { embeds: [new EmbedBuilder().setColor(COLORS.main).setTitle("Application Management").setDescription("Configure forms, questions, automation, requirements, cooldowns and the public panel.").addFields({ name: "Forms", value: String(forms.length), inline: true }, { name: "Questions", value: String(forms.reduce((n, f) => n + (f.questions?.length || 0), 0)), inline: true }, { name: "Review Channel", value: c.reviewChannelId ? `<#${c.reviewChannelId}>` : "Not configured", inline: true })], components: [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("appcfg_create").setLabel("Create Form").setStyle(ButtonStyle.Success), new ButtonBuilder().setCustomId("appcfg_manage").setLabel("Manage Forms").setStyle(ButtonStyle.Primary), new ButtonBuilder().setCustomId("appcfg_settings").setLabel("Settings").setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId("appcfg_publish").setLabel("Publish Panel").setStyle(ButtonStyle.Primary))] }; }
function formManage(c) { const entries = Object.entries(c.forms).slice(0, 25); if (!entries.length) return { embeds: [new EmbedBuilder().setColor(COLORS.main).setTitle("Manage Forms").setDescription("No forms exist yet.")], components: [back()] }; return { embeds: [new EmbedBuilder().setColor(COLORS.main).setTitle("Manage Forms").setDescription("Select a form to manage its questions and automation.")], components: [new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId("appcfg_form").setPlaceholder("Select a form").addOptions(entries.map(([fid, f]) => ({ label: f.name.slice(0, 100), description: `${f.questions?.length || 0} questions`, value: fid, ...(f.emoji ? { emoji: f.emoji } : {}) })))), back()] }; }
function back(to = "appcfg_home") { return new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(to).setLabel("Back").setStyle(ButtonStyle.Secondary)); }
function formPage(c, fid) { const f = form(c, fid); if (!f) return formManage(c); const q = f.questions.map((x, i) => `**${i + 1}.** [${x.type}${x.required ? ", required" : ", optional"}] ${x.label}`).join("\n\n"); return { embeds: [new EmbedBuilder().setColor(COLORS.main).setTitle(formName(f)).setDescription(q || "No questions yet.").addFields({ name: "Required roles", value: f.requiredRoles.length ? f.requiredRoles.map(r => `<@&${r}>`).join(", ") : "None", inline: true }, { name: "Blocked roles", value: f.blockedRoles.length ? f.blockedRoles.map(r => `<@&${r}>`).join(", ") : "None", inline: true }, { name: "Reviewer roles", value: f.reviewerRoles.length ? f.reviewerRoles.map(r => `<@&${r}>`).join(", ") : "None", inline: true }, { name: "Cooldown", value: `${f.cooldownSeconds}s`, inline: true })], components: [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`appcfg_addq:${fid}`).setLabel("Add Question").setStyle(ButtonStyle.Success), new ButtonBuilder().setCustomId(`appcfg_delq:${fid}`).setLabel("Remove Question").setStyle(ButtonStyle.Danger), new ButtonBuilder().setCustomId(`appcfg_delete:${fid}`).setLabel("Delete Form").setStyle(ButtonStyle.Danger)), back("appcfg_manage")] }; }
function createModal() { return new ModalBuilder().setCustomId("appcfg_create_modal").setTitle("Create Application Form").addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId("name").setLabel("Form name").setStyle(TextInputStyle.Short).setMaxLength(100).setRequired(true)), new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId("emoji").setLabel("Emoji (optional)").setStyle(TextInputStyle.Short).setMaxLength(50).setRequired(false))); }
function addQuestionModal(fid) { return new ModalBuilder().setCustomId(`appcfg_qmodal:${fid}`).setTitle("Add Application Question").addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId("label").setLabel("Question").setStyle(TextInputStyle.Paragraph).setMaxLength(1000).setRequired(true)), new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId("type").setLabel("Type: short, paragraph, choice, role, number, yesno").setStyle(TextInputStyle.Short).setMaxLength(20).setRequired(true)), new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId("options").setLabel("Choice options separated by |").setStyle(TextInputStyle.Short).setMaxLength(1000).setRequired(false)), new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId("required").setLabel("Required? yes/no").setStyle(TextInputStyle.Short).setMaxLength(3).setRequired(false)), new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId("regex").setLabel("Regex validation (optional)").setStyle(TextInputStyle.Short).setMaxLength(300).setRequired(false))); }
function removeQuestionModal(fid) { return new ModalBuilder().setCustomId(`appcfg_rqmodal:${fid}`).setTitle("Remove Question").addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId("number").setLabel("Question number").setStyle(TextInputStyle.Short).setMaxLength(3).setRequired(true))); }
function settings() { return { embeds: [new EmbedBuilder().setColor(COLORS.main).setTitle("Application Settings").setDescription("Choose the review channel, application admin role, or default panel channel." )], components: [new ActionRowBuilder().addComponents(new ChannelSelectMenuBuilder().setCustomId("appcfg_review").setPlaceholder("Review channel").setChannelTypes([ChannelType.GuildText])), new ActionRowBuilder().addComponents(new RoleSelectMenuBuilder().setCustomId("appcfg_admin").setPlaceholder("Application admin role")), new ActionRowBuilder().addComponents(new ChannelSelectMenuBuilder().setCustomId("appcfg_panel").setPlaceholder("Default panel channel")), back()] }; }

const command = {
  data: new SlashCommandBuilder().setName("applications").setDescription("Manage and use Super League applications.")
    .addSubcommand(s => s.setName("panel").setDescription("Publish the public application panel.").addChannelOption(o => o.setName("channel").setDescription("Channel").addChannelTypes(ChannelType.GuildText)))
    .addSubcommand(s => s.setName("list").setDescription("List application forms."))
    .addSubcommand(s => s.setName("create").setDescription("Create an application form.").addStringOption(o => o.setName("name").setDescription("Form name").setRequired(true)).addRoleOption(o => o.setName("role").setDescription("Role given on acceptance").setRequired(true)))
    .addSubcommand(s => s.setName("delete").setDescription("Delete an application form.").addStringOption(o => o.setName("application").setDescription("Form ID").setRequired(true).setAutocomplete(true)))
    .addSubcommandGroup(g => g.setName("question").setDescription("Manage form questions.")
      .addSubcommand(s => s.setName("add").setDescription("Add a question.").addStringOption(o => o.setName("application").setDescription("Form ID").setRequired(true).setAutocomplete(true)).addStringOption(o => o.setName("label").setDescription("Question").setRequired(true)).addStringOption(o => o.setName("type").setDescription("short, paragraph, choice, role, number, yesno").setRequired(true)).addStringOption(o => o.setName("options").setDescription("Choice options separated by |").setRequired(false)).addBooleanOption(o => o.setName("required").setDescription("Required").setRequired(false)).addStringOption(o => o.setName("regex").setDescription("Regex validation").setRequired(false)))
      .addSubcommand(s => s.setName("remove").setDescription("Remove a question.").addStringOption(o => o.setName("application").setDescription("Form ID").setRequired(true).setAutocomplete(true)).addIntegerOption(o => o.setName("number").setDescription("Question number").setRequired(true).setMinValue(1)))
      .addSubcommand(s => s.setName("list").setDescription("List questions.").addStringOption(o => o.setName("application").setDescription("Form ID").setRequired(true).setAutocomplete(true))))
    .addSubcommandGroup(g => g.setName("config").setDescription("Configure application settings.")
      .addSubcommand(s => s.setName("review-channel").setDescription("Set review channel.").addChannelOption(o => o.setName("channel").setDescription("Channel").addChannelTypes(ChannelType.GuildText).setRequired(true)))
      .addSubcommand(s => s.setName("admin-role").setDescription("Set application admin role.").addRoleOption(o => o.setName("role").setDescription("Role").setRequired(true)))
      .addSubcommand(s => s.setName("panel-channel").setDescription("Set default panel channel.").addChannelOption(o => o.setName("channel").setDescription("Channel").addChannelTypes(ChannelType.GuildText).setRequired(true)))
      .addSubcommand(s => s.setName("cooldown").setDescription("Set form cooldown.").addStringOption(o => o.setName("application").setDescription("Form ID").setRequired(true).setAutocomplete(true)).addIntegerOption(o => o.setName("seconds").setDescription("Cooldown seconds").setRequired(true).setMinValue(0).setMaxValue(2592000)))
      .addSubcommand(s => s.setName("roles").setDescription("Set required/blocked/reviewer roles.").addStringOption(o => o.setName("application").setDescription("Form ID").setRequired(true).setAutocomplete(true)).addStringOption(o => o.setName("required").setDescription("Required role IDs, comma separated").setRequired(false)).addStringOption(o => o.setName("blocked").setDescription("Blocked role IDs, comma separated").setRequired(false)).addStringOption(o => o.setName("reviewers").setDescription("Reviewer role IDs, comma separated").setRequired(false)))
      .addSubcommand(s => s.setName("action").setDescription("Configure automatic role actions.").addStringOption(o => o.setName("application").setDescription("Form ID").setRequired(true).setAutocomplete(true)).addStringOption(o => o.setName("stage").setDescription("When the action runs").setRequired(true).addChoices({ name: "on submit", value: "submit" }, { name: "on accept", value: "accept" }, { name: "on reject", value: "reject" })).addStringOption(o => o.setName("add").setDescription("Role IDs to add, comma separated").setRequired(false)).addStringOption(o => o.setName("remove").setDescription("Role IDs to remove, comma separated").setRequired(false))))
    .addSubcommand(s => s.setName("export").setDescription("Export application history as JSON.").addStringOption(o => o.setName("application").setDescription("Optional form ID").setRequired(false).setAutocomplete(true))),
  async autocomplete(i) { const c = cfg(loadData(), i.guildId), q = i.options.getFocused().toLowerCase(); await i.respond(Object.entries(c.forms).filter(([, f]) => f.name.toLowerCase().includes(q)).slice(0, 25).map(([value, f]) => ({ value, name: f.name }))); },
  async execute(i) {
    if (!i.guild) return i.reply({ embeds: [createErrorEmbed("This command can only be used in a server.")], ephemeral: true });
    const data = loadData(), c = cfg(data, i.guild.id), group = i.options.getSubcommandGroup(false), sub = i.options.getSubcommand();
    if (!admin(i, c, data)) return i.reply({ embeds: [createErrorEmbed("You do not have permission to manage applications.", i.guild)], ephemeral: true });
    if (!group && sub === "create") { const name = i.options.getString("name", true).trim(), role = i.options.getRole("role", true), fid = slug(name); if (!fid || c.forms[fid]) return i.reply({ embeds: [createErrorEmbed("That form name is invalid or already exists.", i.guild)], ephemeral: true }); if (Object.keys(c.forms).length >= MAX_FORMS) return i.reply({ embeds: [createErrorEmbed(`Maximum of ${MAX_FORMS} forms reached.`, i.guild)], ephemeral: true }); if (!safeApplicationRole(i.guild, role.id)) return i.reply({ embeds: [createErrorEmbed("I cannot assign that role. It must be a normal editable role below my highest role and may not have administrative permissions.", i.guild)], ephemeral: true }); c.forms[fid] = normalizeForm({ name, roleId: role.id, emoji: null, questions: [], actions: { submit: { add: [], remove: [] }, accept: { add: [role.id], remove: [] }, reject: { add: [], remove: [] } }, requiredRoles: [], blockedRoles: [], reviewerRoles: [], cooldownSeconds: 0 }); saveData(data); return i.reply({ embeds: [createSuccessEmbed(i.guild, "Application Form Created", `Created **${name}**.`)], ephemeral: true }); }
    if (!group && sub === "delete") { const fid = i.options.getString("application", true), f = c.forms[fid]; if (!f) return i.reply({ embeds: [createErrorEmbed("That form does not exist.", i.guild)], ephemeral: true }); delete c.forms[fid]; saveData(data); return i.reply({ embeds: [createSuccessEmbed(i.guild, "Application Form Deleted", `Deleted **${f.name}**.`)], ephemeral: true }); }
    if (!group && sub === "list") { const text = Object.entries(c.forms).map(([fid, f]) => `**${fid}** — ${formName(f)} — ${f.questions?.length || 0} questions`).join("\n") || "No forms configured."; return i.reply({ embeds: [new EmbedBuilder().setColor(COLORS.main).setTitle("Application Forms").setDescription(text.slice(0, 4096))], ephemeral: true }); }
    if (!group && sub === "panel") { const ch = i.options.getChannel("channel") || i.guild.channels.cache.get(c.panelChannelId); if (!ch) return i.reply({ embeds: [createErrorEmbed("Configure or specify a panel channel first.", i.guild)], ephemeral: true }); if (!Object.keys(c.forms).length) return i.reply({ embeds: [createErrorEmbed("Create a form first.", i.guild)], ephemeral: true }); const msg = await ch.send(publicPanel(i.guild, c)); c.panelChannelId = ch.id; c.panelMessageId = msg.id; saveData(data); return i.reply({ embeds: [createSuccessEmbed(i.guild, "Application Panel Published", `Published to ${ch}.`)], ephemeral: true }); }
    if (group === "question") { const fid = i.options.getString("application", true), f = form(c, fid); if (!f) return i.reply({ embeds: [createErrorEmbed("That form does not exist.", i.guild)], ephemeral: true }); if (sub === "add") { if (f.questions.length >= MAX_QUESTIONS) return i.reply({ embeds: [createErrorEmbed(`Maximum of ${MAX_QUESTIONS} questions reached.`, i.guild)], ephemeral: true }); const type = i.options.getString("type", true).toLowerCase(), allowed = ["short", "paragraph", "choice", "role", "number", "yesno"]; if (!allowed.includes(type)) return i.reply({ embeds: [createErrorEmbed(`Invalid type. Use: ${allowed.join(", ")}.`, i.guild)], ephemeral: true }); const options = (i.options.getString("options") || "").split("|").map(x => x.trim()).filter(Boolean), regex = i.options.getString("regex") || null; if (type === "choice" && (!options.length || options.length > MAX_OPTIONS)) return i.reply({ embeds: [createErrorEmbed("Choice questions need 1–25 options separated by |.", i.guild)], ephemeral: true }); if (regex) { try { new RegExp(regex); } catch { return i.reply({ embeds: [createErrorEmbed("The regex is invalid.", i.guild)], ephemeral: true }); } } f.questions.push({ id: id(), label: i.options.getString("label", true).trim(), type, required: i.options.getBoolean("required") !== false, options, regex, min: null, max: null, placeholder: null, roleCount: 1 }); saveData(data); return i.reply({ embeds: [createSuccessEmbed(i.guild, "Question Added", `Added **#${f.questions.length}** to **${f.name}**.`)], ephemeral: true }); } if (sub === "remove") { const n = i.options.getInteger("number", true); if (n > f.questions.length) return i.reply({ embeds: [createErrorEmbed("That question does not exist.", i.guild)], ephemeral: true }); f.questions.splice(n - 1, 1); saveData(data); return i.reply({ embeds: [createSuccessEmbed(i.guild, "Question Removed", `Removed question #${n}.`)], ephemeral: true }); } return i.reply({ embeds: [new EmbedBuilder().setColor(COLORS.main).setTitle(`${f.name} Questions`).setDescription(f.questions.map((q, n) => `**${n + 1}.** [${q.type}${q.required ? ", required" : ", optional"}] ${q.label}`).join("\n\n").slice(0, 4096) || "No questions.")], ephemeral: true }); }
    if (group === "config") { const fid = i.options.getString("application", false), f = fid ? form(c, fid) : null; if (sub === "review-channel") { c.reviewChannelId = i.options.getChannel("channel", true).id; saveData(data); return i.reply({ embeds: [createSuccessEmbed(i.guild, "Review Channel Set", `<#${c.reviewChannelId}>`)], ephemeral: true }); } if (sub === "admin-role") { c.adminRoleId = i.options.getRole("role", true).id; saveData(data); return i.reply({ embeds: [createSuccessEmbed(i.guild, "Application Admin Role Set", `<@&${c.adminRoleId}>`)], ephemeral: true }); } if (sub === "panel-channel") { c.panelChannelId = i.options.getChannel("channel", true).id; saveData(data); return i.reply({ embeds: [createSuccessEmbed(i.guild, "Panel Channel Set", `<#${c.panelChannelId}>`)], ephemeral: true }); } if (!f) return i.reply({ embeds: [createErrorEmbed("That form does not exist.", i.guild)], ephemeral: true }); const parse = s => (s || "").split(",").map(x => x.trim()).filter(x => /^\d+$/.test(x)); if (sub === "cooldown") { f.cooldownSeconds = i.options.getInteger("seconds", true); saveData(data); return i.reply({ embeds: [createSuccessEmbed(i.guild, "Cooldown Updated", `${f.name}: ${f.cooldownSeconds}s`)], ephemeral: true }); } if (sub === "roles") { f.requiredRoles = parse(i.options.getString("required")); f.blockedRoles = parse(i.options.getString("blocked")); f.reviewerRoles = parse(i.options.getString("reviewers")); saveData(data); return i.reply({ embeds: [createSuccessEmbed(i.guild, "Form Roles Updated", `${f.name} roles updated.`)], ephemeral: true }); } if (sub === "action") { const stage = i.options.getString("stage", true), add = parse(i.options.getString("add")), remove = parse(i.options.getString("remove")); const unsafe = [...new Set([...add, ...remove])].filter(roleId => !safeApplicationRole(i.guild, roleId)); if (unsafe.length) return i.reply({ embeds: [createErrorEmbed("Every automation role must be a normal editable role below my highest role and may not have administrative permissions.", i.guild)], ephemeral: true }); f.actions[stage] = { add, remove }; saveData(data); return i.reply({ embeds: [createSuccessEmbed(i.guild, "Role Actions Updated", `${f.name}: ${stage} actions saved.`)], ephemeral: true }); } }
    if (!group && sub === "export") { const fid = i.options.getString("application"); const rows = Object.values(c.history).filter(x => !fid || x.applicationId === fid); return i.reply({ content: `Exported ${rows.length} application record(s).`, files: [new AttachmentBuilder(Buffer.from(JSON.stringify(rows, null, 2)), { name: "applications.json" })], ephemeral: true }); }
  }
};

async function start(i, fid) {
  const data = loadData(), c = cfg(data, i.guild.id), f = form(c, fid), member = await i.guild.members.fetch(i.user.id).catch(() => null);
  if (!f || !member) return i.reply({ embeds: [createErrorEmbed("That application is unavailable.", i.guild)], ephemeral: true });
  if (!f.roleId || !safeApplicationRole(i.guild, f.roleId)) return i.reply({ embeds: [createErrorEmbed("This application has an invalid acceptance role configuration.", i.guild)], ephemeral: true });
  if (!f.questions.length) return i.reply({ embeds: [createErrorEmbed("This application has no questions configured yet.", i.guild)], ephemeral: true });
  if (hasBlocked(member, f.blockedRoles)) return i.reply({ embeds: [createErrorEmbed("You cannot apply for this form.", i.guild)], ephemeral: true });
  if (!hasRoles(member, f.requiredRoles)) return i.reply({ embeds: [createErrorEmbed("You do not have the required role(s) for this application.", i.guild)], ephemeral: true });
  const key = `${i.guild.id}:${i.user.id}`; if (data.settings.activeApplications[key]) return i.reply({ embeds: [createErrorEmbed("You already have an active application.", i.guild)], ephemeral: true });
  const prior = Object.values(c.history).filter(x => x.userId === i.user.id && x.applicationId === fid).sort((a, b) => b.submittedAt - a.submittedAt)[0];
  if (prior && f.cooldownSeconds && Date.now() - prior.submittedAt < f.cooldownSeconds * 1000) { const left = Math.ceil((f.cooldownSeconds * 1000 - (Date.now() - prior.submittedAt)) / 1000); return i.reply({ embeds: [createErrorEmbed(`You must wait ${left}s before applying again.`, i.guild)], ephemeral: true }); }
  const state = { guildId: i.guild.id, userId: i.user.id, applicationId: fid, questionIndex: 0, answers: [], startedAt: Date.now() }; data.settings.activeApplications[key] = state; saveData(data); return showQuestion(i, state, false);
}
function activeKey(s) { return `${s.guildId}:${s.userId}`; }
function currentQuestion(f, s) { return f.questions[s.questionIndex]; }
function questionText(q, n, total) { return `**Question ${n + 1}/${total}**\n${q.label}\n\n${q.required ? "Required" : "Optional"}`; }
function skipRow() { return new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("application_skip").setLabel("Skip").setStyle(ButtonStyle.Secondary)); }
async function showQuestion(i, s, update) {
  const data = loadData(), c = cfg(data, s.guildId), f = form(c, s.applicationId), q = currentQuestion(f, s); if (!q) return finish(i, s);
  const rows = []; const embed = new EmbedBuilder().setColor(COLORS.main).setTitle(formName(f)).setDescription(questionText(q, s.questionIndex, f.questions.length));
  if (q.type === "choice") rows.push(new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId("application_choice").setPlaceholder("Select an answer").addOptions(q.options.map((x, n) => ({ label: x.slice(0, 100), value: String(n) })))));
  else if (q.type === "role") rows.push(new ActionRowBuilder().addComponents(new RoleSelectMenuBuilder().setCustomId("application_role").setPlaceholder("Select a role").setMinValues(q.required ? 1 : 0).setMaxValues(Math.min(25, Math.max(1, q.roleCount || 1)))));
  else if (q.type === "yesno") rows.push(new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("application_yes:yes").setLabel("Yes").setStyle(ButtonStyle.Success), new ButtonBuilder().setCustomId("application_yes:no").setLabel("No").setStyle(ButtonStyle.Danger)));
  else rows.push(new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("application_answer").setLabel(q.type === "paragraph" ? "Answer" : "Enter Answer").setStyle(ButtonStyle.Primary)));
  if (!q.required) rows.push(skipRow()); rows.push(new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("application_cancel").setLabel("Cancel").setStyle(ButtonStyle.Danger));
  const payload = { embeds: [embed], components: rows, ephemeral: true }; return update ? i.update(payload) : i.reply(payload);
}
async function saveAnswer(i, answer) {
  const data = loadData(), key = `${i.guild.id}:${i.user.id}`, s = data.settings.activeApplications[key]; if (!s) return i.reply({ embeds: [createErrorEmbed("Your application session expired.", i.guild)], ephemeral: true });
  const c = cfg(data, s.guildId), f = form(c, s.applicationId), q = currentQuestion(f, s); if (!q) return finish(i, s); answer = String(answer ?? "").trim();
  if (!answer && q.required) return i.reply({ embeds: [createErrorEmbed("This question is required.", i.guild)], ephemeral: true });
  if (q.regex && answer) { try { if (!new RegExp(q.regex).test(answer)) return i.reply({ embeds: [createErrorEmbed("That answer does not match the required format.", i.guild)], ephemeral: true }); } catch {} }
  if (q.type === "number" && answer && !Number.isFinite(Number(answer))) return i.reply({ embeds: [createErrorEmbed("Enter a valid number.", i.guild)], ephemeral: true });
  s.answers.push({ questionId: q.id, label: q.label, type: q.type, value: answer }); s.questionIndex++; saveData(data); return showQuestion(i, s, true);
}
async function finish(i, s) {
  const data = loadData(), c = cfg(data, s.guildId), f = form(c, s.applicationId); if (!f) return i.reply({ embeds: [createErrorEmbed("This application no longer exists.", i.guild)], ephemeral: true }); if (!c.reviewChannelId) return i.reply({ embeds: [createErrorEmbed("The review channel is not configured.", i.guild)], ephemeral: true });
  const channel = i.guild.channels.cache.get(c.reviewChannelId); if (!channel?.isTextBased()) return i.reply({ embeds: [createErrorEmbed("The configured review channel is unavailable.", i.guild)], ephemeral: true });
  const rid = id(), review = { id: rid, guildId: s.guildId, userId: s.userId, applicationId: s.applicationId, applicationName: f.name, roleId: f.roleId, questions: f.questions, answers: s.answers, status: "pending", submittedAt: Date.now() };
  c.submissions[rid] = review; c.history[rid] = review; delete data.settings.activeApplications[activeKey(s)]; saveData(data); await applyRoleActions(i.guild, s.userId, actionsFor(f, "submit"), `Submitted application ${rid}`);
  const fields = s.answers.map((a, n) => ({ name: `Q${n + 1}: ${a.label}`.slice(0, 256), value: (a.value || "No answer").slice(0, 1024) }));
  const embed = new EmbedBuilder().setColor(COLORS.pending).setTitle(`${f.name} Application`).setDescription(`**Applicant:** <@${s.userId}>\n**Status:** Pending\n**Review ID:** \`${rid}\``).addFields(fields).setTimestamp();
  const row = new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`application_accept:${rid}`).setLabel("Accept").setStyle(ButtonStyle.Success), new ButtonBuilder().setCustomId(`application_reject:${rid}`).setLabel("Reject").setStyle(ButtonStyle.Danger));
  try { await channel.send({ embeds: [embed], components: [row] }); } catch { review.status = "delivery_failed"; saveData(data); return i.reply({ embeds: [createErrorEmbed("The application was saved but could not be sent to the review channel.", i.guild)], ephemeral: true }); }
  return i.reply({ embeds: [new EmbedBuilder().setColor(COLORS.accept).setTitle("Application Submitted").setDescription(`Your **${f.name}** application was submitted successfully. You will be notified after review.`)], ephemeral: true });
}
async function applyRoleActions(guild, userId, actions, reason) { const member = await guild.members.fetch(userId).catch(() => null); if (!member) return; for (const rid of roleList(actions.remove)) { if (safeApplicationRole(guild, rid)) await member.roles.remove(rid, reason).catch(() => {}); } for (const rid of roleList(actions.add)) { if (!safeApplicationRole(guild, rid)) continue; const role = guild.roles.cache.get(rid); if (role) await member.roles.add(role, reason).catch(() => {}); } }
async function review(i, accepted, rid) {
  const data = loadData(), c = cfg(data, i.guildId), r = c.submissions[rid] || c.history[rid]; if (!r) return i.reply({ content: "Application review not found.", ephemeral: true }); const f = form(c, r.applicationId); if (!f) return i.reply({ content: "The form no longer exists.", ephemeral: true }); if (!reviewer(i, c, data, f)) return i.reply({ content: "You do not have permission to review applications.", ephemeral: true }); if (r.status !== "pending") return i.reply({ content: `This application is already ${r.status}.`, ephemeral: true });
  if (!accepted) return i.showModal(new ModalBuilder().setCustomId(`application_reject_modal:${rid}`).setTitle("Reject Application").addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId("reason").setLabel("Reason").setStyle(TextInputStyle.Paragraph).setMaxLength(1000).setRequired(false))));
  r.status = "accepted"; r.reviewedBy = i.user.id; r.reviewedAt = Date.now(); r.reason = null; saveData(data); await applyRoleActions(i.guild, r.userId, actionsFor(f, "accept"), `Accepted application ${rid}`); await notify(i, r, true, null); return updateReviewMessage(i, r, true);
}
async function reject(i, rid, reason) { const data = loadData(), c = cfg(data, i.guildId), r = c.submissions[rid] || c.history[rid]; if (!r) return i.reply({ content: "Application review not found.", ephemeral: true }); const f = form(c, r.applicationId); if (!f) return i.reply({ content: "The form no longer exists.", ephemeral: true }); if (!reviewer(i, c, data, f)) return i.reply({ content: "You do not have permission to review applications.", ephemeral: true }); if (r.status !== "pending") return i.reply({ content: `This application is already ${r.status}.`, ephemeral: true }); r.status = "rejected"; r.reviewedBy = i.user.id; r.reviewedAt = Date.now(); r.reason = reason || "No reason provided"; saveData(data); await applyRoleActions(i.guild, r.userId, actionsFor(f, "reject"), `Rejected application ${rid}`); await notify(i, r, false, r.reason); return updateReviewMessage(i, r, false); }
async function notify(i, r, accepted, reason) { const u = await i.client.users.fetch(r.userId).catch(() => null); if (!u) return; await u.send(accepted ? `Your **${r.applicationName}** application in **${i.guild.name}** was **accepted**.` : `Your **${r.applicationName}** application in **${i.guild.name}** was **rejected**.\nReason: ${reason}`).catch(() => {}); }
async function updateReviewMessage(i, r, accepted) { const e = i.message?.embeds?.[0] ? EmbedBuilder.from(i.message.embeds[0]) : new EmbedBuilder(); e.setColor(accepted ? COLORS.accept : COLORS.reject).setDescription(`**Applicant:** <@${r.userId}>\n**Status:** ${accepted ? "Accepted" : "Rejected"}\n**Reviewed by:** <@${r.reviewedBy}>${r.reason ? `\n**Reason:** ${r.reason}` : ""}`).setTimestamp(); return i.update({ embeds: [e], components: [] }); }
async function handleApplicationSelect(i) { return start(i, i.values[0]); }
async function handleApplicationDM() {}
async function handleApplicationReview(i) { const [action, rid] = i.customId.split(":"); return review(i, action === "application_accept", rid); }
async function handleInteraction(i) {
  if (!i.guild || !i.customId?.startsWith("appcfg_")) return; const data = loadData(), c = cfg(data, i.guild.id); if (!admin(i, c, data)) return i.reply({ embeds: [createErrorEmbed("Only application administrators can use this panel.", i.guild)], ephemeral: true }); const x = i.customId;
  if (i.isButton()) { if (x === "appcfg_home") return i.update(adminHome(i.guild, c)); if (x === "appcfg_manage") return i.update(formManage(c)); if (x === "appcfg_settings") return i.update(settings()); if (x === "appcfg_publish") { const ch = i.guild.channels.cache.get(c.panelChannelId); if (!ch) return i.reply({ embeds: [createErrorEmbed("Set the panel channel first.", i.guild)], ephemeral: true }); const msg = await ch.send(publicPanel(i.guild, c)); c.panelMessageId = msg.id; saveData(data); return i.reply({ embeds: [createSuccessEmbed(i.guild, "Application Panel Published", `Published to ${ch}.`)], ephemeral: true }); } if (x === "appcfg_create") return i.showModal(createModal()); if (x.startsWith("appcfg_addq:")) return i.showModal(addQuestionModal(x.split(":")[1])); if (x.startsWith("appcfg_delq:")) return i.showModal(removeQuestionModal(x.split(":")[1])); if (x.startsWith("appcfg_delete:")) { const fid = x.split(":")[1]; delete c.forms[fid]; saveData(data); return i.update(formManage(c)); } }
  if (i.isStringSelectMenu() && x === "appcfg_form") return i.update(formPage(c, i.values[0]));
  if (i.isChannelSelectMenu?.()) { if (x === "appcfg_review") c.reviewChannelId = i.values[0]; else if (x === "appcfg_panel") c.panelChannelId = i.values[0]; saveData(data); return i.update(settings()); }
  if (i.isRoleSelectMenu?.() && x === "appcfg_admin") { c.adminRoleId = i.values[0]; saveData(data); return i.update(settings()); }
  if (i.isRoleSelectMenu?.() && x.startsWith("appcfg_create_role:")) { const fid = x.split(":")[1], f = c.forms[fid], role = i.guild.roles.cache.get(i.values[0]); if (!f || !safeApplicationRole(i.guild, role?.id)) return i.reply({ embeds: [createErrorEmbed("That role cannot be used. Choose a normal editable role below my highest role without administrative permissions.", i.guild)], ephemeral: true }); f.roleId = role.id; f.actions ??= {}; f.actions.accept ??= { add: [], remove: [] }; f.actions.accept.add = roleList(f.actions.accept.add).filter(rid => safeApplicationRole(i.guild, rid)); if (!f.actions.accept.add.includes(role.id)) f.actions.accept.add.push(role.id); saveData(data); return i.update({ embeds: [createSuccessEmbed(i.guild, "Acceptance Role Set", `${f.name} will give ${role} when accepted.`)], components: [] }); }
  if (i.isModalSubmit()) {
    if (x === "appcfg_create_modal") { const name = i.fields.getTextInputValue("name").trim(), emoji = i.fields.getTextInputValue("emoji").trim() || null, fid = slug(name); if (!fid || c.forms[fid]) return i.reply({ embeds: [createErrorEmbed("That form name is invalid or already exists.", i.guild)], ephemeral: true }); c.forms[fid] = normalizeForm({ name, emoji, roleId: null, questions: [], actions: { submit: { add: [], remove: [] }, accept: { add: [], remove: [] }, reject: { add: [], remove: [] } } }); saveData(data); return i.reply({ embeds: [new EmbedBuilder().setColor(COLORS.main).setTitle("Choose Acceptance Role").setDescription(`Form: **${name}**\n\nSelect the role accepted applicants should receive.`)], components: [new ActionRowBuilder().addComponents(new RoleSelectMenuBuilder().setCustomId(`appcfg_create_role:${fid}`).setPlaceholder("Select acceptance role"))], ephemeral: true }); }
    if (x.startsWith("appcfg_qmodal:")) { const fid = x.split(":")[1], f = form(c, fid), label = i.fields.getTextInputValue("label").trim(), type = i.fields.getTextInputValue("type").trim().toLowerCase(), options = i.fields.getTextInputValue("options").split("|").map(v => v.trim()).filter(Boolean), regex = i.fields.getTextInputValue("regex").trim() || null, required = i.fields.getTextInputValue("required").trim().toLowerCase() !== "no"; if (!f || !["short","paragraph","choice","role","number","yesno"].includes(type)) return i.reply({ embeds: [createErrorEmbed("Invalid form or question type.", i.guild)], ephemeral: true }); if (type === "choice" && (!options.length || options.length > 25)) return i.reply({ embeds: [createErrorEmbed("Choice questions need 1–25 options.", i.guild)], ephemeral: true }); if (regex) { try { new RegExp(regex); } catch { return i.reply({ embeds: [createErrorEmbed("Invalid regex.", i.guild)], ephemeral: true }); } } f.questions.push({ id: id(), label, type, required, options, regex, min: null, max: null, placeholder: null, roleCount: 1 }); saveData(data); return i.reply({ embeds: [createSuccessEmbed(i.guild, "Question Added", `Added **#${f.questions.length}**.`)], ephemeral: true }); }
    if (x.startsWith("appcfg_rqmodal:")) { const fid = x.split(":")[1], f = form(c, fid), n = Number(i.fields.getTextInputValue("number")); if (!f || !Number.isInteger(n) || n < 1 || n > f.questions.length) return i.reply({ embeds: [createErrorEmbed("Invalid question number.", i.guild)], ephemeral: true }); f.questions.splice(n - 1, 1); saveData(data); return i.reply({ embeds: [createSuccessEmbed(i.guild, "Question Removed", `Removed question #${n}.`)], ephemeral: true }); }
  }
}
async function handleApplicantInteraction(i) {
  if (!i.guild) return;
  if (i.isModalSubmit() && i.customId.startsWith("application_reject_modal:")) { const rid = i.customId.split(":")[1], reason = i.fields.getTextInputValue("reason").trim() || "No reason provided"; return reject(i, rid, reason); }
  const data = loadData(), key = `${i.guild.id}:${i.user.id}`, s = data.settings.activeApplications[key]; if (!s) return i.reply({ embeds: [createErrorEmbed("Your application session expired.", i.guild)], ephemeral: true });
  if (i.customId === "application_cancel") { delete data.settings.activeApplications[key]; saveData(data); return i.update({ embeds: [createErrorEmbed("Application cancelled.", i.guild)], components: [] }); }
  if (i.customId === "application_skip") return saveAnswer(i, "");
  if (i.customId === "application_answer") { const c = cfg(data, s.guildId), f = form(c, s.applicationId), q = currentQuestion(f, s); const modal = new ModalBuilder().setCustomId("application_answer_modal").setTitle("Application Answer").addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId("answer").setLabel(q.label.slice(0, 45)).setStyle(q.type === "paragraph" ? TextInputStyle.Paragraph : TextInputStyle.Short).setRequired(q.required))); return i.showModal(modal); }
  if (i.customId.startsWith("application_yes:")) return saveAnswer(i, i.customId.endsWith(":yes") ? "Yes" : "No");
  if (i.isStringSelectMenu() && i.customId === "application_choice") { const c = cfg(data, s.guildId), f = form(c, s.applicationId), q = currentQuestion(f, s); return saveAnswer(i, q.options[Number(i.values[0])] || ""); }
  if (i.isRoleSelectMenu?.() && i.customId === "application_role") return saveAnswer(i, i.values.map(r => `<@&${r}>`).join(", "));
  if (i.isModalSubmit() && i.customId === "application_answer_modal") return saveAnswer(i, i.fields.getTextInputValue("answer"));
}
module.exports = { command, handleInteraction, handleApplicationSelect, handleApplicationDM, handleApplicationReview, handleApplicantInteraction };
