"use strict";

const fs = require("fs");
const path = require("path");
const { SlashCommandBuilder, PermissionFlagsBits, ActionRowBuilder, ButtonBuilder, ButtonStyle, RoleSelectMenuBuilder, ChannelSelectMenuBuilder, ChannelType, ModalBuilder, TextInputBuilder, TextInputStyle, EmbedBuilder } = require("discord.js");

const dbPath = path.resolve(process.env.SUPER_LEAGUE_DB_PATH || path.join(__dirname, "users.json"));
const filePath = path.join(path.dirname(dbPath), "levels.json");
const cache = new Map();
const cooldowns = new Map();
const guildQueues = new Map();
const DANGEROUS_PERMISSIONS = [
    PermissionFlagsBits.Administrator,
    PermissionFlagsBits.ManageGuild,
    PermissionFlagsBits.ManageRoles,
    PermissionFlagsBits.ManageChannels,
    PermissionFlagsBits.BanMembers,
    PermissionFlagsBits.KickMembers,
    PermissionFlagsBits.ManageWebhooks
];
const DEFAULTS = { enabled: true, xpMin: 15, xpMax: 25, cooldownSeconds: 60, baseXp: 100, exponent: 2, ignoredChannels: [], announcementChannel: null, announcementEnabled: true, levelRoles: {} };

function loadAll() { try { if (!fs.existsSync(filePath)) return {}; const data = JSON.parse(fs.readFileSync(filePath, "utf8")); return data && typeof data === "object" ? data : {}; } catch (error) { console.error("Failed to load levels database:", error); return {}; } }
function saveAll(data) { fs.mkdirSync(path.dirname(filePath), { recursive: true }); const tmp = `${filePath}.tmp-${process.pid}-${Date.now()}`; fs.writeFileSync(tmp, JSON.stringify(data, null, 2), { mode: 0o600 }); fs.renameSync(tmp, filePath); }
function guildConfig(guildId) { if (!cache.has(guildId)) { const all = loadAll(); const raw = all[guildId] || {}; cache.set(guildId, { ...DEFAULTS, ...raw, ignoredChannels: [...(raw.ignoredChannels || [])], levelRoles: { ...(raw.levelRoles || {}) } }); } return cache.get(guildId); }
function persistGuild(guildId) { const all = loadAll(); const members = all[guildId]?.members || {}; all[guildId] = { ...guildConfig(guildId), members }; saveAll(all); }
function memberData(guildId, userId) { const all = loadAll(); all[guildId] ||= {}; all[guildId].members ||= {}; all[guildId].members[userId] ||= { xp: 0 }; return { all, data: all[guildId].members[userId] }; }
function xpForLevel(level, cfg) { return Math.floor(cfg.baseXp * Math.pow(level, cfg.exponent)); }
function levelFromXp(xp, cfg) { let level = 0; while (level < 1000 && xp >= xpForLevel(level + 1, cfg)) level++; return level; }
function randomXp(cfg) { return Math.floor(Math.random() * (cfg.xpMax - cfg.xpMin + 1)) + cfg.xpMin; }
function safeLevelRole(role) { return Boolean(role && !role.managed && role.id !== role.guild.id && role.editable && !role.permissions.has(DANGEROUS_PERMISSIONS)); }
function withGuildLock(guildId, task) { const previous = guildQueues.get(guildId) || Promise.resolve(); const current = previous.then(task, task); guildQueues.set(guildId, current); return current.finally(() => { if (guildQueues.get(guildId) === current) guildQueues.delete(guildId); }); }
async function applyLevelRole(member, level, cfg) { const eligible = Object.entries(cfg.levelRoles).map(([required, roleId]) => [Number(required), roleId]).filter(([required, roleId]) => Number.isInteger(required) && required > 0 && roleId && required <= level).sort((a,b) => b[0]-a[0]); const targetRole = eligible.map(([, roleId]) => member.guild.roles.cache.get(roleId)).find(role => safeLevelRole(role)); if (!targetRole) return; const configured = new Set(Object.values(cfg.levelRoles)); for (const roleId of configured) { const role = member.guild.roles.cache.get(roleId); if (roleId !== targetRole.id && safeLevelRole(role) && member.roles.cache.has(roleId)) await member.roles.remove(roleId).catch(() => {}); } if (!member.roles.cache.has(targetRole.id)) await member.roles.add(targetRole).catch(() => {}); }
async function handleMessage(message) { if (!message.guild || message.author.bot || !message.member) return; const cfg = guildConfig(message.guild.id); if (!cfg.enabled || cfg.ignoredChannels.includes(message.channel.id)) return; return withGuildLock(message.guild.id, async () => { const key = `${message.guild.id}:${message.author.id}`; const now = Date.now(); if (now - (cooldowns.get(key) || 0) < cfg.cooldownSeconds * 1000) return; cooldowns.set(key, now); const { all, data } = memberData(message.guild.id, message.author.id); const oldLevel = levelFromXp(data.xp || 0, cfg); data.xp = Math.max(0, Math.floor(data.xp || 0) + randomXp(cfg)); const newLevel = levelFromXp(data.xp, cfg); all[message.guild.id].members[message.author.id] = data; saveAll(all); if (newLevel <= oldLevel) return; await applyLevelRole(message.member, newLevel, cfg); if (cfg.announcementEnabled) { const channel = cfg.announcementChannel ? message.guild.channels.cache.get(cfg.announcementChannel) : message.channel; if (channel?.isTextBased()) await channel.send(`🎉 ${message.author} reached **Level ${newLevel}**!`).catch(() => {}); } }); }
function embed(title, description, color = 0x5865f2) { return new EmbedBuilder().setColor(color).setTitle(title).setDescription(description); }
function mainPage(guild) { const c=guildConfig(guild.id); const roles=Object.entries(c.levelRoles).sort((a,b)=>Number(a[0])-Number(b[0])).map(([l,r])=>`Level ${l}: <@&${r}>`).join("\n")||"None configured"; return { embeds:[embed("Levels Configuration", `**Status:** ${c.enabled?"Enabled":"Disabled"}\n**XP:** ${c.xpMin}-${c.xpMax} per message\n**Cooldown:** ${c.cooldownSeconds}s\n**Curve:** ${c.baseXp} × level^${c.exponent}\n**Announcement:** ${c.announcementEnabled?(c.announcementChannel?`<#${c.announcementChannel}>`:"Current channel"):"Disabled"}\n**Ignored channels:** ${c.ignoredChannels.length}\n\n**Level roles**\n${roles}`)], components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("lvlcfg_general").setLabel("General").setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId("lvlcfg_xp").setLabel("XP & Curve").setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId("lvlcfg_roles").setLabel("Level Roles").setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId("lvlcfg_channels").setLabel("Channels").setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId("lvlcfg_reset").setLabel("Reset Data").setStyle(ButtonStyle.Danger)),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("lvlcfg_refresh").setLabel("Refresh").setStyle(ButtonStyle.Secondary))] }; }
function back(){return new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("lvlcfg_home").setLabel("Back").setStyle(ButtonStyle.Secondary));}
function modal(id,title,fields){const m=new ModalBuilder().setCustomId(id).setTitle(title);for(const [key,label,value] of fields)m.addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId(key).setLabel(label).setStyle(TextInputStyle.Short).setRequired(true).setValue(String(value))));return m;}
function generalPage(guild){const c=guildConfig(guild.id);return {embeds:[embed("General",`Current status: **${c.enabled?"Enabled":"Disabled"}**\n\nConfigure whether members earn XP and whether level-up announcements are enabled.`)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("lvlcfg_toggle").setLabel(c.enabled?"Disable Levels":"Enable Levels").setStyle(c.enabled?ButtonStyle.Danger:ButtonStyle.Success),new ButtonBuilder().setCustomId("lvlcfg_toggle_ann").setLabel(c.announcementEnabled?"Disable Announcements":"Enable Announcements").setStyle(ButtonStyle.Secondary)),back()]};}
function xpPage(guild){const c=guildConfig(guild.id);return {embeds:[embed("XP & Curve",`**XP per message:** ${c.xpMin}-${c.xpMax}\n**Cooldown:** ${c.cooldownSeconds}s\n**Base XP:** ${c.baseXp}\n**Exponent:** ${c.exponent}\n\nLevel requirement: **base XP × level^exponent**.`)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("lvlcfg_xp_edit").setLabel("Edit XP Settings").setStyle(ButtonStyle.Primary)),back()]};}
function rolesPage(guild){return {embeds:[embed("Level Roles","Configure which role is awarded at each level. The highest configured level at or below a member's level wins.")],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("lvlcfg_role_add").setLabel("Add / Change Role").setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId("lvlcfg_role_remove").setLabel("Remove Level Role").setStyle(ButtonStyle.Danger)),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("lvlcfg_role_list").setLabel("View Roles").setStyle(ButtonStyle.Secondary)),back()]};}
function channelsPage(guild){const c=guildConfig(guild.id);return {embeds:[embed("Channels",`**Announcement channel:** ${c.announcementChannel?`<#${c.announcementChannel}>`:"Current message channel"}\n**Ignored channels:** ${c.ignoredChannels.length}`)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("lvlcfg_announce_channel").setLabel("Announcement Channel").setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId("lvlcfg_ignore_channel").setLabel("Add Ignored Channel").setStyle(ButtonStyle.Secondary)),back()]};}
const command={data:new SlashCommandBuilder().setName("levels").setDescription("Level and XP system").addSubcommand(s=>s.setName("config").setDescription("Open the level configuration panel")).addSubcommand(s=>s.setName("rank").setDescription("View a member's level and XP").addUserOption(o=>o.setName("member").setDescription("Member to inspect").setRequired(false))).addSubcommand(s=>s.setName("leaderboard").setDescription("View the server XP leaderboard")),async execute(interaction){if(!interaction.guild)return interaction.reply({embeds:[embed("Error","This command can only be used in a server.",0xed4245)],ephemeral:true});const sub=interaction.options.getSubcommand();if(sub==="config"){if(interaction.guild.ownerId!==interaction.user.id)return interaction.reply({embeds:[embed("Error","Only the server owner can configure levels.",0xed4245)],ephemeral:true});return interaction.reply(mainPage(interaction.guild));}const cfg=guildConfig(interaction.guild.id);if(sub==="rank"){const member=interaction.options.getMember("member")||interaction.member;const {data}=memberData(interaction.guild.id,member.id);const xp=data.xp||0,level=levelFromXp(xp,cfg),current=xpForLevel(level,cfg),next=xpForLevel(level+1,cfg),progress=Math.max(0,Math.min(100,Math.round(((xp-current)/Math.max(1,next-current))*100))),bars=Math.round(progress/10);return interaction.reply({embeds:[embed(`${member.displayName}'s Rank`,`**Level ${level}**\n**${xp.toLocaleString()} XP**\n\n${"█".repeat(bars)}${"░".repeat(10-bars)} ${progress}%\n${Math.max(0,xp-current).toLocaleString()} / ${Math.max(1,next-current).toLocaleString()} XP to next level`)]});}const all=loadAll(),members=Object.entries(all[interaction.guild.id]?.members||{}).map(([id,d])=>({id,xp:d.xp||0})).sort((a,b)=>b.xp-a.xp).slice(0,10);if(!members.length)return interaction.reply({embeds:[embed("Leaderboard","No XP has been earned yet.")]});return interaction.reply({embeds:[embed("XP Leaderboard",members.map((m,i)=>`**${i+1}.** <@${m.id}> — Level ${levelFromXp(m.xp,cfg)} • ${m.xp.toLocaleString()} XP`).join("\n"))]});}};
async function handleInteraction(interaction){if(!interaction.guild)return;if(interaction.guild.ownerId!==interaction.user.id)return interaction.reply({embeds:[embed("Error","Only the server owner can use this configuration panel.",0xed4245)],ephemeral:true});const id=interaction.customId;if(interaction.isButton()){if(id==="lvlcfg_home"||id==="lvlcfg_refresh")return interaction.update(mainPage(interaction.guild));if(id==="lvlcfg_general")return interaction.update(generalPage(interaction.guild));if(id==="lvlcfg_xp")return interaction.update(xpPage(interaction.guild));if(id==="lvlcfg_roles")return interaction.update(rolesPage(interaction.guild));if(id==="lvlcfg_channels")return interaction.update(channelsPage(interaction.guild));if(id==="lvlcfg_toggle"){const c=guildConfig(interaction.guild.id);c.enabled=!c.enabled;persistGuild(interaction.guild.id);return interaction.update(generalPage(interaction.guild));}if(id==="lvlcfg_toggle_ann"){const c=guildConfig(interaction.guild.id);c.announcementEnabled=!c.announcementEnabled;persistGuild(interaction.guild.id);return interaction.update(generalPage(interaction.guild));}if(id==="lvlcfg_xp_edit"){const c=guildConfig(interaction.guild.id);return interaction.showModal(modal("lvlcfg_modal_xp","XP & Curve",[["min","Minimum XP",c.xpMin],["max","Maximum XP",c.xpMax],["cooldown","Cooldown seconds",c.cooldownSeconds],["base","Base XP",c.baseXp],["exponent","Curve exponent",c.exponent]]));}if(id==="lvlcfg_role_add")return interaction.showModal(modal("lvlcfg_modal_role","Level Role",[["level","Level number",1]]));if(id==="lvlcfg_role_remove")return interaction.showModal(modal("lvlcfg_modal_role_remove","Remove Level Role",[["level","Level number",1]]));if(id==="lvlcfg_role_list")return interaction.reply({embeds:[embed("Configured Level Roles",Object.entries(guildConfig(interaction.guild.id).levelRoles).sort((a,b)=>Number(a[0])-Number(b[0])).map(([l,r])=>`Level ${l}: <@&${r}>`).join("\n")||"None configured")],ephemeral:true});if(id==="lvlcfg_reset"){const all=loadAll();if(all[interaction.guild.id]){all[interaction.guild.id].members={};saveAll(all);}return interaction.update(mainPage(interaction.guild));}if(id==="lvlcfg_announce_channel")return interaction.update({embeds:[embed("Announcement Channel","Select the channel where level-ups should be announced.")],components:[new ActionRowBuilder().addComponents(new ChannelSelectMenuBuilder().setCustomId("lvlcfg_set_announce").setPlaceholder("Select channel").setChannelTypes([ChannelType.GuildText]).setMinValues(1).setMaxValues(1)),back()]});if(id==="lvlcfg_ignore_channel")return interaction.update({embeds:[embed("Ignored Channel","Select a channel where messages should not award XP.")],components:[new ActionRowBuilder().addComponents(new ChannelSelectMenuBuilder().setCustomId("lvlcfg_add_ignore").setPlaceholder("Select channel").setChannelTypes([ChannelType.GuildText]).setMinValues(1).setMaxValues(1)),back()]});}
if(interaction.isChannelSelectMenu()){const channel=interaction.channels.first(),c=guildConfig(interaction.guild.id);if(id==="lvlcfg_set_announce")c.announcementChannel=channel.id;if(id==="lvlcfg_add_ignore"&&!c.ignoredChannels.includes(channel.id))c.ignoredChannels.push(channel.id);persistGuild(interaction.guild.id);return interaction.update(channelsPage(interaction.guild));}
if(interaction.isRoleSelectMenu()&&id.startsWith("lvlcfg_set_role:")){const level=Number(id.split(":")[1]),role=interaction.roles.first(),c=guildConfig(interaction.guild.id);if(!safeLevelRole(role))return interaction.reply({embeds:[embed("Error","Choose a normal, non-managed role below my highest role without administrative permissions.",0xed4245)],ephemeral:true});c.levelRoles[level]=role.id;persistGuild(interaction.guild.id);return interaction.update({embeds:[embed("Saved",`Level ${level} now awards ${role}.`)],components:[]});}
if(interaction.isModalSubmit()){const c=guildConfig(interaction.guild.id);if(id==="lvlcfg_modal_xp"){const v=k=>Number(interaction.fields.getTextInputValue(k));if(!["min","max","cooldown","base","exponent"].every(k=>Number.isFinite(v(k))))return interaction.reply({embeds:[embed("Error","All values must be valid numbers.",0xed4245)],ephemeral:true});c.xpMin=Math.max(0,Math.min(1000,Math.floor(v("min"))));c.xpMax=Math.max(c.xpMin,Math.min(1000,Math.floor(v("max"))));c.cooldownSeconds=Math.max(0,Math.min(86400,Math.floor(v("cooldown"))));c.baseXp=Math.max(1,Math.min(1000000,Math.floor(v("base"))));c.exponent=Math.max(1,Math.min(4,v("exponent")));persistGuild(interaction.guild.id);return interaction.reply({embeds:[embed("Saved","XP and curve settings updated.")],ephemeral:true});}if(id==="lvlcfg_modal_role"){const level=Number(interaction.fields.getTextInputValue("level"));if(!Number.isFinite(level))return interaction.reply({embeds:[embed("Error","Level must be a number.",0xed4245)],ephemeral:true});const safeLevel=Math.max(1,Math.min(1000,Math.floor(level)));return interaction.reply({embeds:[embed("Select Role",`Select the Discord role to assign at level ${safeLevel}.`)],components:[new ActionRowBuilder().addComponents(new RoleSelectMenuBuilder().setCustomId(`lvlcfg_set_role:${safeLevel}`).setPlaceholder("Select role").setMinValues(1).setMaxValues(1))],ephemeral:true});}if(id==="lvlcfg_modal_role_remove"){const level=Math.max(1,Math.floor(Number(interaction.fields.getTextInputValue("level"))));delete c.levelRoles[level];persistGuild(interaction.guild.id);return interaction.reply({embeds:[embed("Saved",`Removed the role for level ${level}.`)],ephemeral:true});}}
}
module.exports={command,handleMessage,handleInteraction};
